/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DuNguyn Studio (https://sketchfab.com/dunguyn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-pack-chibi-base-mesh-rigged-fed4fb329f224f1594f631eae8d2626b
Title: Free Pack - Chibi Base Mesh (Rigged)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    BaseMesh_Chibi_M: THREE.MeshStandardMaterial
    lambert1: THREE.MeshPhysicalMaterial
  }
}

 function ChibiMesh(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models_3d/chibi.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_7.geometry}
          material={materials.BaseMesh_Chibi_M}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_9.geometry}
          material={materials.lambert1}
          skeleton={nodes.Object_9.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models_3d/chibi.glb');
export default ChibiMesh;
